### ISSUE TITLE
ppcoin specific checks

### ISSUE THREAD

**Issue by kac-** [mably/btcchain#3]
- [x] [not coinbase and not coinstake](https://github.com/ppcoin/ppcoin/blob/v0.4.0ppc/src/main.cpp#L461)
- [x] [min tx amount](https://github.com/ppcoin/ppcoin/blob/v0.4.0ppc/src/main.cpp#L464)
- [ ] [coinbase/stake as individual](https://github.com/ppcoin/ppcoin/blob/v0.4.0ppc/src/main.cpp#L507) /mempool/
- [ ] [locktime beyond 2038](https://github.com/ppcoin/ppcoin/blob/v0.4.0ppc/src/main.cpp#L514) /mempool/
- [x] [prevTx time before time](https://github.com/ppcoin/ppcoin/blob/v0.4.0ppc/src/main.cpp#L1178)
- [x] [coinstake earns reward](https://github.com/ppcoin/ppcoin/blob/v0.4.0ppc/src/main.cpp#L1232)
- [x] [enforce tx fees for all blocks](https://github.com/ppcoin/ppcoin/blob/v0.4.0ppc/src/main.cpp#L1249)
- [x] [coinstake in wrong position](https://github.com/ppcoin/ppcoin/blob/v0.4.0ppc/src/main.cpp#L1853)
- [x] [empty coinbase output in PoS block](https://github.com/ppcoin/ppcoin/blob/v0.4.0ppc/src/main.cpp#L1858)
- [x] [coinstake timestamp](https://github.com/ppcoin/ppcoin/blob/v0.4.0ppc/src/main.cpp#L1866)
- [x] [block timestamp earlier than tx timestamp](https://github.com/ppcoin/ppcoin/blob/v0.4.0ppc/src/main.cpp#L1881)
- [x] [block signature](https://github.com/ppcoin/ppcoin/blob/v0.4.0ppc/src/main.cpp#L1910)
- [x] [duplicated stake](https://github.com/ppcoin/ppcoin/blob/v0.4.0ppc/src/main.cpp#L1985)

**Comment by mably** [comment]
This issue was moved to ppcsuite/ppcd#2
